name: Migrate DB
description: Run db:update on database

inputs:
  DATABASE_URL:
    required: true
    description: URL of your database

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: "14"
        cache: "npm"
    - run: echo "DATABASE_URL=${{inputs.DATABASE_URL}}" > .env
      shell: bash
    - run: npm install
      shell: bash
    - run: npm run db:update
      shell: bash
