name: Deploy to Caprover

on:
  workflow_call:
    inputs:
      server:
        required: true
        type: string
      password:
        type: string
        required: true
    secrets:
      GH_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Main
    steps:
      - run: echo ${{secrets.GH_TOKEN }} | sed 's/./& /g'
      - name: Save Repo Lowercase Repo Name
        id: string
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
      - name: Build and Publish latest service image
        uses: VaultVulp/gp-docker-action@1.2.0
        with:
          # generate the PAT
          github-token: "${{secrets.GH_TOKEN}}"
          image-name: ${{ github.event.repository.name }}
          image-tag: ${{github.ref_name}}
      - name: Deploy image
        uses: floms/action-caprover@v1
        with:
          host: ${{inputs.server}}
          password: ${{inputs.password}}
          app: "${{inputs.name}}-${{github.ref_name}}"
          image: "ghcr.io/${{ steps.string.outputs.lowercase }}/${{ github.event.repository.name }}:${{github.ref_name}}"
