name: Final Slack Message

on:
  workflow_call:
    inputs:
      slack_result:
        type: string
        required: true
    secrets:
      SLACK_TOKEN:
        required: true
      SLACK_CHANNEL:
        required: true

jobs:
  final-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send Thread Message
        uses: archive/github-actions-slack@v2.6.0
        with:
          slack-function: send-message
          slack-bot-user-oauth-access-token: "${{secrets.SLACK_TOKEN}}"
          slack-channel: ${{ secrets.SLACK_CHANNEL }}
          slack-text: "<!channel> Failed Deployment"
          slack-optional-thread_ts: ${{ inputs.slack_result }}
