name: Final Slack Message

on:
  workflow_call:
    inputs:
      slack_result:
        type: string
        required: true
    secrets:
      SLACK_TOKEN:
        required: true

jobs:
  final-slack:
    environment: Main
    runs-on: ubuntu-latest
    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1
      - name: Send Thread Message
        uses: archive/github-actions-slack@v2.4.0
        if: success()
        with:
          slack-function: update-message
          slack-bot-user-oauth-access-token: "${{secrets.SLACK_TOKEN}}"
          slack-channel: ${{ fromJson(inputs.slack_result).response.channel }}
          slack-update-message-text: "Deploy for <https://github.com/${{ github.repository }} |  ${{ github.repository }}> *${{github.ref_name}}*. View Progress <https://github.com/${{ github.repository }}/actions/runs/${{github.run_id}}?check_suite_focus=true | Here>. :white_check_mark:"
          slack-update-message-ts: ${{ fromJson(inputs.slack_result).response.message.ts }}

      - name: Send Thread Message
        uses: archive/github-actions-slack@v2.4.0
        if: failure()
        with:
          slack-function: send-message
          slack-bot-user-oauth-access-token: "${{secrets.SLACK_TOKEN}}"
          slack-channel: ${{ fromJson(inputs.slack_result).response.channel }}
          slack-text: "<@U013CG61YMA> Failed Deployment"
          slack-optional-thread_ts: ${{ fromJson(inputs.slack_result).response.message.ts }}
