name: Final Slack Message

on:
  workflow_call:
    inputs:
      slack_result:
        type: string
        required: true
    secrets:
      SLACK_TOKEN:
        required: true
      SLACK_CHANNEL:
        required: true

jobs:
  final-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send Thread Message
        uses: archive/github-actions-slack@v2.6.0
        with:
          slack-function: send-reaction
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: ${{ fromJson(steps.send-message.outputs.slack-result).response.channel }}
          slack-emoji-name: white_check_mark
          slack-message-timestamp: ${{ fromJson(steps.send-message.outputs.slack-result).response.message.ts }}
